[providers]
  node = "18"

[phases.setup]
  nixPkgs = ["...", "chromium", "nss", "freetype", "harfbuzz", "pango", "xorg.libX11", "xorg.libXrandr", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "alsa-lib", "mesa", "expat"]

[phases.build]
  cmds = ["npm ci", "npm run build"]

[start]
  cmd = "npm run start"
